config/routes.rb
Rails.application.routes.draw do

 match 'signup', to: 'authentication#signup', via: [:get, :post]
 match 'login',  to: 'authentication#login',  via: [:get, :post]
 get   'logout', to: 'authentication#logout'
 get   'confirm/:id', to: 'authentication#confirm_email'

  resources :books
  resources :authors
  resources :categories
  resources :users
  resources :authentication
  resources :favorites

   root 'books#index'

  get 'admin', to: "user#index"

  get 'users/remove_admin/:id', to: "users#remove_admin"
  get 'users/make_admin/:id', to: "users#make_admin"

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books, dependent: :destroy
	validates :name, presence: {message: "of the author is required."}, length: {maximum: 25, message: "can not be longer that 25 characters."}, uniqueness: true
	validates :country, presence: {message: "of the author is required."}, length: {in: 3..50, message: "must be between 3 and 50 characters."}

 # It returns the authors whose names contain one or more words that form the query
  def self.search(query)
    # where(:name, query) -> This would return an exact match of the query
      where("name like ? OR country like ?", "%#{query}%", "%#{query}%")
  end


	# TODO - add here the validation that the book has a title

	def books_titles
		titles = []
		self.books.each do |book|
			titles << book.title
		end
		titles.join(", ")

	end

	def book_number
		titles = []
		self.books.each do |book|
			titles << book.title
		end
		books = Hash.new(0)
		titles.each { |b| books[b] += 1}
		return books.count
	end

	

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
     if params[:search]
      @authors = Author.search(params[:search]).order("name ASC")
    else
      @authors = Author.order("name ASC")
    end

  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :country)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      
      <th>Name</th>
      <th>Country</th>
      <th>Number of Books</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        
        <td><%= author.name %></td>
        <td><%= author.country %></td>
        <td><%= author.book_number %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<head>
  <title>Simple Search Form</title>
</head>
<body>
  <!-- When submit the form, the view rendered will be the index view of our articles resource -->
  <%= form_tag(authors_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Authors" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
      <button class="btn" type="submit"><i class="icon-search"></i></button>
    </div>
  <% end %>
  <%= yield %>
</body>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @author.country %>
</p>

<p>
  <strong>Books:</strong>
  <%= @author.books_titles %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>